### ISSUE TITLE
lockerProvider throws error when trying to setDefaultDriver

### ISSUE THREAD

**Issue by cheahkhing** [tymondesigns/angular-locker#15]
I tried to use lockerProvider, but it seems like it's not working as documented:

.config(['lockerProvider', function config(lockerProvider) {
    lockerProvider.setDefaultDriver('session')
                  .setDefaultNamespace('myAppName')
                  .setSeparator('.')
                  .setEventsEnabled(false);
}]);

I tried to search for the configuration in the source code, I don't see any of them. Is this still supported?

**Comment by tymondesigns** [comment]
It is still supported for the current version (1.2.1)

The master branch is going to be the next release and I have simplified the way to provide defaults to the lockerProvider - see [here](https://github.com/tymondesigns/angular-locker/blob/master/changes.md)
