### ISSUE TITLE
README out of date

### ISSUE THREAD

**Issue by jaredmcateer** [tymondesigns/angular-locker#16]
in https://github.com/tymondesigns/angular-locker/commit/7e0393dc0b029badfc196f71461e0446880ee91a you removed the helper methods to set defaults in the provider but the documention in the README still indicates they can be used. If I get time this week I'll put in a pull request if no one has already.

**Comment by jaredmcateer** [comment]
I see you've already noted this... this is my bad for using the master instead of releases.

**Comment by tymondesigns** [comment]
No worries. v2.0.0 is now released! :)
