### ISSUE TITLE
Documentation Request - 100% Angular Fallback

### ISSUE THREAD

**Issue by tmcgee123** [tymondesigns/angular-locker#28]
In the midst of supporting private browsing on Safari (it doesn't allow webstorage), our product owner wanted a fallback for storage.

The solution we've provided was a temporary storage fallback, utilizing Angular's ```$cacheFactory``` and a decorator for angular-locker.

[Here is a link to the Gist.](https://gist.github.com/tmcgee123/c25325d70277b2ee3f3a)

Would this be something you would want to provide in the case someone did not want to use Remy's polfill that utilizes cookies for a fallback? I realize that this is not as permanent as a cookie (refreshing will wipe the $cacheFactory values), but some people might want something Angular driven.

This is just a suggestion, any thoughts, comments, or criticisms would be highly appreciated as this is a code that is live on a production level website (tens of thousands of users a day).

**Comment by tymondesigns** [comment]
merged
