### ISSUE TITLE
Doc should encourage minification-friendly practice

### ISSUE THREAD

**Issue by bonatoc** [tymondesigns/angular-locker#6]
.factory('MyFactory', function MyFactory(locker) {
    locker.put('someKey', 'someVal');
    });

should be : 

    .factory('MyFactory', ['locker', function MyFactory(locker) {
    locker.put('someKey', 'someVal');
    }]);

**Comment by tymondesigns** [comment]
Yea I suppose that would help people new to the framework.. job done

Thanks
