### ISSUE TITLE
Plans to add TTL or other expiration concept?

### ISSUE THREAD

**Issue by uberspeck** [tymondesigns/angular-locker#7]
Are there any plans to add TTL features? jStorage, for example, has a TTL feature that's pretty useful. I'd make a pull request but, to be honest, not too confident in my ability to implement it cleanly

**Comment by tymondesigns** [comment]
Hmm.. Not sure about that one. My concern is that I don't want the library to do too much, and become bloated with features that would rarely be useful. 

Can you provide a scenario where you think this would be useful?

**Comment by uberspeck** [comment]
In my case I'm using local storage as a cache to reduce server requests. however I want the cached data to "expire" after a set time to prevent old data from hanging around. i can do this externally to angular-locker, but it would be awesome to just pass a TTL when setting data

**Comment by tymondesigns** [comment]
OK I see what you mean. I will have a think as to how I would implement it, and probably throw together a quick prototype and see where I get.

Thanks!

**Comment by uberspeck** [comment]
awesome! Thanks for looking into it!

**Comment by tymondesigns** [comment]
decided not to add this for now.. might look at it again at some point
